"""categorias

Revision ID: 1a79bbeae1ea
Revises: 2e3a817e3a0f
Create Date: 2026-09-13 21:14:13.679714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a79bbeae1ea'
down_revision: Union[str, Sequence[str], None] = '2e3a817e3a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('direcao', sa.String(length=7), nullable=False),
    sa.Column('protegida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_parent_id'), 'categorias', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categorias_user_id'), 'categorias', ['user_id'], unique=False)
    # NOTA (não gerada pelo Alembic): esta coluna é acrescentada NOT NULL,
    # sem "server_default", a uma tabela "movimentos" já existente (ver a
    # migração anterior, 2e3a817e3a0f) — só é segura porque, nesta altura
    # do projecto, essa tabela ainda não tinha NENHUMA linha (a tabela
    # "categorias" ainda nem existia). Esta migração NUNCA deve ser
    # reproduzida contra uma base de dados que já tenha movimentos
    # gravados — falharia (Postgres não tem valor nenhum para preencher
    # as linhas existentes). Se algum dia for preciso repetir esta cadeia
    # de migrações contra dados reais, este passo tem de mudar para
    # "nullable=True" + um preenchimento explícito + só depois
    # "ALTER COLUMN ... SET NOT NULL".
    op.add_column('movimentos', sa.Column('categoria_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_movimentos_categoria_id'), 'movimentos', ['categoria_id'], unique=False)
    op.create_foreign_key(None, 'movimentos', 'categorias', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimentos', type_='foreignkey')
    op.drop_index(op.f('ix_movimentos_categoria_id'), table_name='movimentos')
    op.drop_column('movimentos', 'categoria_id')
    op.drop_index(op.f('ix_categorias_user_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_parent_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
