"""criar tabela movimentos

Revision ID: 2e3a817e3a0f
Revises: ae4bb10c15a3
Create Date: 2026-09-04 20:19:25.091330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3a817e3a0f'
down_revision: Union[str, Sequence[str], None] = 'ae4bb10c15a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentos_conta_id'), 'movimentos', ['conta_id'], unique=False)
    op.create_index(op.f('ix_movimentos_data'), 'movimentos', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentos_data'), table_name='movimentos')
    op.drop_index(op.f('ix_movimentos_conta_id'), table_name='movimentos')
    op.drop_table('movimentos')
    # ### end Alembic commands ###
