"""ordem_categorias

Revision ID: 50daa75ac214
Revises: 1a79bbeae1ea
Create Date: 2026-09-13 22:35:42.246269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50daa75ac214'
down_revision: Union[str, Sequence[str], None] = '1a79bbeae1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('ordem', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'ordem')
    # ### end Alembic commands ###
