"""ordem_categorias

Revision ID: 50daa75ac214
Revises: 1a79bbeae1ea
Create Date: 2026-09-13 22:35:42.246269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50daa75ac214'
down_revision: Union[str, Sequence[str], None] = '1a79bbeae1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA (não gerada pelo Alembic): tal como em 1a79bbeae1ea (a coluna
    # "categoria_id" de "movimentos"), esta coluna NOT NULL sem
    # "server_default" só é segura porque a tabela "categorias" ainda não
    # tinha nenhuma linha nesta altura do projecto. Nunca reproduzir esta
    # migração contra uma base de dados com categorias já gravadas sem
    # primeiro mudar para "nullable=True" + preenchimento + "SET NOT NULL".
    op.add_column('categorias', sa.Column('ordem', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'ordem')
    # ### end Alembic commands ###
