"""id_transacao_externa_em_movimentos

Revision ID: 52acc3fd255b
Revises: 9cab07075459
Create Date: 2026-09-27 16:25:57.736330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52acc3fd255b'
down_revision: Union[str, Sequence[str], None] = '9cab07075459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentos', sa.Column('id_transacao_externa', sa.String(), nullable=True))
    op.create_index('ux_movimentos_conta_id_id_transacao_externa', 'movimentos', ['conta_id', 'id_transacao_externa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_movimentos_conta_id_id_transacao_externa', table_name='movimentos')
    op.drop_column('movimentos', 'id_transacao_externa')
    # ### end Alembic commands ###
