"""ligacoes_bancarias_e_contas_ligadas

Revision ID: 9cab07075459
Revises: 6b8f3d2a9e17
Create Date: 2026-09-27 15:01:01.537043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cab07075459'
down_revision: Union[str, Sequence[str], None] = '6b8f3d2a9e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligacoes_bancarias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('aspsp_nome', sa.String(length=120), nullable=False),
    sa.Column('aspsp_pais', sa.String(length=2), nullable=False),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_ligacoes_bancarias_user_id'), 'ligacoes_bancarias', ['user_id'], unique=False)
    op.create_table('contas_ligadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ligacao_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('identification_hash', sa.String(), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('nome_titular', sa.String(length=200), nullable=True),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ligacao_id'], ['ligacoes_bancarias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_ligadas_ligacao_id'), 'contas_ligadas', ['ligacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contas_ligadas_ligacao_id'), table_name='contas_ligadas')
    op.drop_table('contas_ligadas')
    op.drop_index(op.f('ix_ligacoes_bancarias_user_id'), table_name='ligacoes_bancarias')
    op.drop_table('ligacoes_bancarias')
    # ### end Alembic commands ###
