"""autorizacoes_pendentes

Revision ID: 9e30c4da4f96
Revises: 52acc3fd255b
Create Date: 2026-09-27 17:25:32.151612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e30c4da4f96'
down_revision: Union[str, Sequence[str], None] = '52acc3fd255b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autorizacoes_pendentes',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_autorizacoes_pendentes_user_id'), 'autorizacoes_pendentes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autorizacoes_pendentes_user_id'), table_name='autorizacoes_pendentes')
    op.drop_table('autorizacoes_pendentes')
    # ### end Alembic commands ###
