"""criar tabela contas

Revision ID: ae4bb10c15a3
Revises: 127c3e11cc4f
Create Date: 2026-09-01 13:55:11.004066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4bb10c15a3'
down_revision: Union[str, Sequence[str], None] = '127c3e11cc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('banco', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('data_ancora', sa.Date(), nullable=False),
    sa.Column('saldo_ancora', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_user_id'), 'contas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contas_user_id'), table_name='contas')
    op.drop_table('contas')
    # ### end Alembic commands ###
